// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciixbycvzaexsdearmmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpaXhieWN2emFleHNkZWFybW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTAxODEsImV4cCI6MjA2NjAyNjE4MX0.CzlgT9xoV0AC1YEdLCpurCDmFVWp-OqG1L4KxsLCDMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);